# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup ibmcloud
      run: |
        wget -O ibmcloud.tgz "https://clis.cloud.ibm.com/download/bluemix-cli/1.1.0/linux64/archive"
        tar -xzf ibmcloud.tgz
        echo "::add-path::~/IBM_Cloud_CLI"

    - name: Use ibmcloud
      run: |
       ibmcloud -h
